### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by kayvax** [ThomasHabets/bthelper#1]
Hi,
I found your project and wanted to try it out. I have used rfcomm method earlier for emergency bluetooth connection and wanted to give your software a try. I have paired both devices but I clearly have some issue with connection. While bt-listener has configurable port, there is no way to set connection port for bt-connecter. And I am kinda confused how it does know target port. 

I managed to get such an error message:

```
connect(): Connection refused
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
```
I can see in bluetoothctl that both devices connect and pair.

**Comment by ThomasHabets** [comment]
The connection port is part of the command line for `bt-connecter`. In the README example:

```
ssh -oProxyCommand="bt-connecter AA:BB:CC:XX:YY:ZZ 2" myhostname-console
```

The `2` after `ZZ` is the port.

**Comment by kayvax** [comment]
I figured out my issue.
When compiled using PKGBUILD I made on Archlinux ARM bt-listener dumps core when I try to connect.
I compiled it manually and it works.

Will need to investigate further what I am breaking.

**Comment by kayvax** [comment]
I have found the source of the bt-listener crash.
When I compile manually the compiler flags are:
```
  C++ Compiler...: g++ -g -O2 -std=c++17 
  Linker.........: /usr/bin/ld  -lutil 
```
And when I compile with makepkg flags are set to:
```
  C++ Compiler...: g++ -march=native -O2 -pipe -fstack-protector-strong -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -Wp,-D_GLIBCXX_ASSERTIONS -std=c++17 
  Linker.........: /usr/bin/ld -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -luti
```
And the crash:
`/usr/include/c++/12.1.0/bits/stl_vector.h:1142: std::vector<_Tp, _Alloc>::const_reference std::vector<_Tp, _Alloc>::operator[](size_type) const [with _Tp = char; _Alloc = std::allocator<char>; const_reference = const char&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.`

Googling that I found it is connected to `-Wp,-D_GLIBCXX_ASSERTIONS` compiler flag.

There is some talk about this issue on the [Fedora mailing list](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/TMDJMX2OYE7Z2WHKXMOMTOBDHJKZJ3NV/) that I am really not qualified to comment on. 

For now modified my files to remove that flag and bt-listener works.

**Comment by ThomasHabets** [comment]
Thanks a lot for the full build args. I was able to reproduce it in a smaller test and fix it.

I don't have good access to do an end to end reproduction over bluetooth this week, so that'll have to wait until next week. But my fix is "obviously correct", so shouldn't break anything at least.

Don't hesitate to reopen if this is still broken for you.
